### ISSUE TITLE
Mac build: Find dmgbuild successor

### ISSUE THREAD

**Issue by hoffie** [jamulussoftware/jamulus#1797]
We are using `dmgbuild` in the Mac build process. 
The `dmgbuild` author has declared to stop maintenance on the project, so we may want to be extra careful here:
- Maybe keep the version pinning from #1796 (would not have been the first time that used open source projects are abandoned and taken over by hostile new maintainers)
- Maybe consider alternatives (`create-dmg` has been linked in other places, not sure if it does the same job?). Edit: Seems to be way more popular/feature-rich as well, https://github.com/create-dmg/create-dmg

Also:
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in links: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpibNJYX
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (41.2.0)
Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (20.3.4)
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
```

I had a quick stab at py3 support (c66d8666), but gave up after problems within biplist code.

cc @ann0see @softins @nefarius2001

**Comment by hoffie** [comment]
This might become a priority at some point, because dmgbuild no longer works out of the box on macos-11:
```
Successfully installed biplist-1.0.3 dmgbuild-1.4.2 ds-store-1.3.0 mac-alias-2.2.0
hdiutil: unflatten: verb not recognized
Usage: /usr/bin/hdiutil <verb> <options>
[...]
Traceback (most recent call last):
  File "/Users/runner/Library/Python/2.7/bin/dmgbuild", line 36, in <module>
    dmgbuild.build_dmg(args.filename, args.volume_name, args.settings, defines=defines, lookForHiDPI=args.lookForHiDPI)
  File "/Users/runner/Library/Python/2.7/lib/python/site-packages/dmgbuild/core.py", line 648, in build_dmg
    raise DMGError('Unable to unflatten to add license')
dmgbuild.core.DMGError: Unable to unflatten to add license
```

https://github.com/al45tair/dmgbuild/issues/29

**Comment by ann0see** [comment]
See #2207
